
# create the API.md file
apidocs:
    #!/bin/bash

    # requires all dev-dependencies to be installed. see pyproject.toml

    BUILD_DIR=/tmp/h3ch-doc-build
    mkdir -p $BUILD_DIR
    export SPHINX_APIDOC_OPTIONS="members,undoc-members,show-inheritance"

    maturin develop

    # https://stackoverflow.com/questions/36237477/python-docstrings-to-github-readme-md
    sphinx-apidoc -o $BUILD_DIR ukis_h3cellstorepy sphinx-apidoc --ext-autodoc --full
    pushd $BUILD_DIR
    make markdown
    popd
    cp $BUILD_DIR/_build/markdown/ukis_h3cellstorepy.md API.md


build-prod:
    #!/bin/bash

    # see https://github.com/pola-rs/polars/blob/9a3066943eda6a0b96807b4d6f6271645a4c55cc/.github/deploy_manylinux.sh#L12
    #export RUSTFLAGS='-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma'
    export RUSTFLAGS='-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx'

    maturin build --release --strip

